DROP TABLE "Kanjis";
DROP TABLE "Meanings";
DROP TABLE "KunReadings";
DROP TABLE "OnReadings";

CREATE TABLE "Kanjis" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"HeisingID"	INTEGER NOT NULL UNIQUE,
	"Kanji"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE "Meanings" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"HeisingID"	INTEGER NOT NULL,
	"Meaning"	TEXT,
	"HeisingMeaning"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE "KunReadings" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"HeisingID"	INTEGER NOT NULL,
	"Reading"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);

CREATE TABLE "OnReadings" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"HeisingID"	INTEGER NOT NULL,
	"Reading"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
);